### ISSUE TITLE
 Error: The "react" package in this environment is not configured correctly

### ISSUE THREAD

**Issue by mohamedmansour** [eknkc/ssr-benchmark#18]
I am running on a windows environment, how do I enable react-server condition?
```
PS C:\Code\ssr-benchmark> npm start

> ssr-benchmark@1.0.0 start
> cross-env NODE_ENV=production node src/index.js

[nitro] [uncaughtException] Error: The "react" package in this environment is not configured correctly. The "react-server" condition must be enabled in any environment that runs React Server Components.
    at 834 (file:///C:/Code/ssr-benchmark/modules/mfng/dist/index.js:1:351385)
    at r (file:///C:/Code/ssr-benchmark/modules/mfng/dist/index.js:1:381887)
    at 645 (file:///C:/Code/ssr-benchmark/modules/mfng/dist/index.js:1:369081)
    at r (file:///C:/Code/ssr-benchmark/modules/mfng/dist/index.js:1:381887)
    at file:///C:/Code/ssr-benchmark/modules/mfng/dist/index.js:1:382140
    at file:///C:/Code/ssr-benchmark/modules/mfng/dist/index.js:1:384657
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async file:///C:/Code/ssr-benchmark/src/index.js:43:14
```

**Comment by eknkc** [comment]
@unstubbable might be interested

**Comment by espacioobligado** [comment]
> To unblock, I just removed the `mfng`

someone explain plssss :(
